<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{3804045a-1986-48f3-bfb8-d7f2d97468a2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	n : UDINT := 5;
	result : ULINT;
	f : Factorial;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[result := f(n);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>